package
{
	public class Texts
	{
		
		public static const _tutorial:Array = new Array(
		"WELCOME TO THE TUTORIAL LEVEL OF TROLLEY PROBLEM."+
		"\n\n(PRESS SPACE)",
		"IN TROLLEY PROBLEM YOU WILL MAKE ETHICAL DECISIONS ABOUT WHAT WILL HAPPEN TO PEOPLE TIED TO TRAIN TRACKS."+
		"\n\n(PRESS SPACE)",
		"ON EACH LEVEL, AN OUT OF CONTROL TROLLEY WILL RUN DOWN TRACKS LIKE THE ONES ABOVE TOWARD PEOPLE WHO WILL DIE IF IT HITS THEM."+
		"\n\n(PRESS SPACE)",
		"EACH TIME YOU WILL DECIDE WHO LIVES AND WHO DIES."+
		"\n\n(PRESS SPACE)",
		"BEFORE STARTING THE REAL LEVELS, YOU CAN TRY THIS OUT IN A SITUATION IN WHICH NO ONE IS IN DANGER."+
		"\n\n(PRESS SPACE)",
		"WHEN THE LEVEL BEGINS, THE TROLLEY WILL RUN DOWN THESE TRACKS FROM LEFT TO RIGHT."+
		"\n\n(PRESS SPACE)",
		"IF YOU WANT TO REDIRECT THE TROLLEY TO THE UPPER TRACK, PRESS THE SPACE BAR TO PULL THE SWITCH BEFORE THE TROLLEY REACHES THE BRANCHING POINT."+
		"\n\n(PRESS SPACE)",
		"IF YOU DON'T WANT TO REDIRECT THE TROLLEY, DO NOTHING AND THE TROLLEY WILL PROCEED ON THE LOWER TRACK."+
		"\n\n(PRESS SPACE)",
		"YOU ONLY GET ONE CHANCE TO PULL THE SWITCH, SO YOU SHOULD PROBABLY DECIDE WHAT YOU'RE GOING TO DO NOW, BEFORE THE LEVEL BEGINS."+
		"\n\n(PRESS SPACE)",
		"ARE YOU READY? REMEMBER YOU CAN EITHER PRESS THE SPACE BAR TO PULL THE SWITCH AND CHANGE THE TRACKS, OR DO NOTHING."+
		"\n\n(PRESS SPACE TO START THE LEVEL)"
		);
		
		public static const _standard:Array = new Array(
		"WELCOME TO LEVEL ONE OF TROLLEY PROBLEM."+
		"\n\n(PRESS SPACE)",
		"UNLIKE THE TUTORIAL LEVEL, THIS TIME THERE ARE PEOPLE TIED TO THE TRACKS WHO WILL BE KILLED IF THE TROLLEY HITS THEM. " +
		"THERE ARE THREE PEOPLE TIED TO THE LOWER TRACK, AND THERE IS ONE PERSON TIED TO THE UPPER TRACK."+
		"\n\n(PRESS SPACE)",
		"YOU CAN PRESS THE SPACE BAR TO PULL THE SWITCH THAT WILL DIRECT THE TROLLEY TO THE UPPER TRACK AND ONE PERSON WILL BE KILLED." +
		"\n\n(PRESS SPACE)",
		"OR YOU CAN DO NOTHING AND THREE PEOPLE WILL BE KILLED."+
		"\n\n(PRESS SPACE)",
		"READY? YOUR DECISION IS IMPORTANT THIS TIME SO TRY TO DO THE RIGHT THING."+
		"\n\n(PRESS SPACE TO START THE LEVEL)"
		);
		
		public static const _loop:Array = new Array(
		"WELCOME TO LEVEL TWO OF TROLLEY PROBLEM."+
		"\n\n(PRESS SPACE)",
		"AS IN LEVEL ONE, THERE ARE THREE PEOPLE TIED TO THE LOWER TRACK AND THERE IS ONE PERSON TIED TO THE UPPER TRACK."+
		"\n\n(PRESS SPACE)",
		"THIS TIME, THE PERSON ON THE UPPER TRACK IS VERY LARGE, SO THE TROLLEY WILL STOP AFTER IT HITS THEM. " +
		"THE TROLLEY WILL ALSO STOP AFTER HITTING THREE PEOPLE IN A ROW."+
		"\n\n(PRESS SPACE)",
		"THE TRACK FOR THIS LEVEL LOOPS AROUND. THIS MEANS THAT IF YOU PULL THE SWITCH YOU ARE USING THE DEATH "+
		"OF THE VERY LARGE PERSON TO STOP THE TROLLEY BEFORE IT HITS THE THREE OTHER PEOPLE."+
		"\n\n(PRESS SPACE)",
		"READY? YOUR DECISION IS IMPORTANT SO TRY TO DO THE RIGHT THING."+
		"\n\n(PRESS SPACE TO START THE LEVEL)"
		);
		
		public static const _shove:Array = new Array(
		"WELCOME TO LEVEL THREE OF TROLLEY PROBLEM."+
		"\n\n(PRESS SPACE)",
		"FOR THIS LEVEL THERE IS ONLY ONE TRACK. THREE PEOPLE ARE TIED TO THE END OF THE TRACK AND " +
		"A VERY LARGE PERSON IS STANDING ON A PLATFORM NEXT TO THE TRACK."+
		"\n\n(PRESS SPACE)",
		"THIS TIME, YOU CAN PRESS THE SPACE BAR TO SHOVE THE VERY LARGE PERSON IN FRONT OF THE MOVING TROLLEY. " +
		"THIS WILL STOP THE TROLLEY BUT WILL KILL THE VERY LARGE PERSON."+
		"\n\n(PRESS SPACE)",
		"OR YOU CAN DO NOTHING, IN WHICH CASE THE THREE PEOPLE WILL BE KILLED."+
		"\n\n(PRESS SPACE)",
		"READY? YOUR DECISION IS IMPORTANT SO TRY TO DO THE RIGHT THING."+
		"\n\n(PRESS SPACE TO START THE LEVEL)"
		);
		
		public static var _personal:Array = new Array(
		"WELCOME TO LEVEL FOUR OF TROLLEY PROBLEM."+
		"\n\n(PRESS SPACE)",
		"THIS LEVEL IS IDENTICAL TO LEVEL ONE OTHER THAN A SINGLE DIFFERENCE." +
		"\n\n(PRESS SPACE)",
		"THIS TIME THE PERSON TIED TO THE UPPER TRACK IS SOMEONE IMPORTANT TO YOU. PLEASE INDICATE WHO IT IS BY TYPING THE APPROPRIATE LETTER: "+
		"(M)OTHER, (F)ATHER, (B)ROTHER, (S)ISTER, (W)IFE, (H)USBAND, B(O)YFRIEND, (G)IRLFRIEND, (D)AUGHTER, SO(N).",
		"AS IN LEVEL ONE YOU CAN PRESS THE SPACE BAR TO PULL THE SWITCH THAT WILL DIRECT THE TROLLEY TO THE UPPER TRACK OR YOU CAN DO NOTHING."+
		"\n\n(PRESS SPACE)",
		"READY? YOUR DECISION IS IMPORTANT SO TRY TO DO THE RIGHT THING."+
		"\n\n(PRESS SPACE TO START THE LEVEL)"
		);

		public static var _results:Array = new Array();
		
		public function Texts() {
		}
	}
}